version: "3.8"
services:
 python-server:
  build:
   context: ../
   dockerfile: docker/Dockerfile1
  volumes:
   - ../python/:/python/
  ports:
   - 3000:3000
 tool-pytest:
  build:
   context: ../
   dockerfile: docker/Dockerfile2
  volumes:
   - ../python/:/project/python/
   - ../tests/:/project/tests/
